### ISSUE TITLE
BSC

### ISSUE THREAD

**Issue by yanrising** [flashbots/searcher-sponsored-tx#19]
Its work for Binance Chain Network?

**Comment by Sadboipoor** [comment]
analysis/webservice/algorithms_spark/MaximaMinimaSpark.py

**Comment by blockinator** [comment]
@yanrising did you figure it out?

**Comment by yanrising** [comment]
Not yet. Any ideas?

**Comment by blockinator** [comment]
I was able to work through most of the errors and just have this one:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit
```

So I will have to come up with a way to estimate gas and add it to the code. What errors are you running into?

**Comment by yanrising** [comment]
Error: cannot estimate gas; transaction may fail or may require manual gas limit too
I think need add fix price fee

**Comment by 12r3r3** [comment]
pls can you enlighten how it works for Binance Chain Network
